### PR TITLE
Simplify the code to parse a color.

### PR DESCRIPTION
**Pull request by zephyr**
I just saw justforfunc №5 and tried to do the homework. I think this is simpler.

But one question: Do you find it clearer to write `uint8(n >> 8)` or `uint8(n >> 8 & 0xff)`? The second is more verbose in what it’s doing, but i kinda like the shorter version.

And btw, thanks for #JustForFunc!

### CODE REVIEW

**Comment by zephyr** [comment]
Ups, my code was actually wrong, even if it passed the tests. Fixed both :).

**Review by campoy — APPROVED** [review]

**Comment by campoy** [comment]
hey @googlebot, can you check the CLA?

**Comment by campoy** [comment]
apparently @googlebot took the day off today
in order to accept your contributions I'd need to you to sign this CLA @zephyr https://cla.developers.google.com/

thanks

**Comment by zephyr** [comment]
I signed it! @campoy

**Comment by campoy** [comment]
wait, why did you close it? can't merge it now 😢

**Comment by zephyr** [comment]
Sorry – since the change is so small, i squashed the three commits into one and send a new pull reqest #19. I didn’t thought about that this would be more complicated for you. Will not happen again!

**Pull request closed without merging**
