### PR TITLE
tmux support

### PR DESCRIPTION
**Pull request by gamefiend**
_This PR is followup for campoy/tools#11._

Added in tmux support, and found out that it works with the caveat being that full inline support of images will need the iterm2 tmux integration to work.  tmux doesn't know where to position the cursor after iterm2 places it, so tmux places the cursor over it 
screen shot 2017-09-01 at 1 22 01 pm

comparing to tmux integration support (`tmux -CC`) which 
screen shot 2017-09-01 at 1 24 03 pm

I make a note of this in the code and in the docs.  It definitely works, and I think there is a way to add a special tmux size option...but that is for another PR, methinks!

### CODE REVIEW

**Comment by gamefiend** [comment]
I signed it!

**Comment by campoy** [comment]
hey, sorry for the bad timing but decided to move to a new API to be able to print many images given a single writer ... and now your PR is full of conflicts

would you mind updating it? otherwise I can probably do it later on

**Comment by gamefiend** [comment]
yeah, np! I'll start hacking away on it this weekend.

**Comment by gamefiend** [comment]
OK, finally got it all in there! I added in the tmux detection in a way more conformant to how `IsSupported` is used, using that as the basis to set `headerEscape` and `footerEscape` (which I honestly like a lot better than the if-else-iness of my last version). Added in the capability of a TMUX_TEST variable to control whether we are matching `tmux` for testing.

I didn't write any tests with tmux on this pass, but wasn't sure if we wanted to create a `tmux` version of the `TestEncode` and `TestGoodWriter` functions. If that seems like a good approach, let me know and i'll implement. (maybe in a new PR?)

**Review by campoy — APPROVED** [review]

**Pull request merged**
